version: "3.8"

services:
  client:
    build: .
    volumes:
      - ".:/app"
      - "node_modules:/app/node_modules"
      - "npm_cache:/root/.npm"
    ports:
      - 4200:4200
    stdin_open: true
    tty: true

volumes:
  node_modules:
  npm_cache:
