version: '3.8'

services:
  api:
    build:
      context: ./api
      target: dev
    volumes:
      - './api:/app'
      - 'rubygems:/usr/local/bundle'
      - 'tmp:/app/tmp'
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    networks:
      - 'backend'

  client:
    build:
      context: ./client
      target: dev
    volumes:
      - './client:/app'
      - 'node_modules:/app/node_modules'
    ports:
      - '4200:4200'
    stdin_open: true
    tty: true
    networks:
      - 'frontend'
      - 'backend'

  db:
    image: postgres:13-alpine
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
      - '.:/app'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      PGPASSWORD: postgres
    networks:
      - 'backend'

volumes:
  rubygems:
  node_modules:
  tmp:
  pgdata:

networks:
  frontend:
  backend:
